inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - examples/**/*
    - vendor/**/*
    - gemfiles/vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*_spec.rb"

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false
